name: FFNx

run-name: 1.24.2.${{ github.run_number }}

on:
  workflow_dispatch:
  push:
    branches:
    - master
    tags:
    - "*"
  pull_request:
    branches:
    - master

env:
  _IS_BUILD_CANARY: false
  _IS_GITHUB_RELEASE: false
  _RELEASE_NAME: FFNx
  _RELEASE_VERSION: v0
  _RELEASE_CONFIGURATION: Release
  _BUILD_BRANCH: "${{ github.ref }}"
  _CHANGELOG_VERSION: "0"
  # GIT: Fix reporting from stderr to stdout
  GIT_REDIRECT_STDERR: 2>&1

jobs:
  FFNx:
    runs-on: windows-latest
    timeout-minutes: 1440
    strategy:
      max-parallel: 1
    steps:
    - name: Set Git Config
      run: |
        git config --global core.autocrlf false
        git config --global core.filemode false
        git config --global core.longpaths true
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0
    - name: Build
      run: ".github/workflows/build.ps1"
      shell: pwsh
      env:
        _BUILD_VERSION: "1.24.2.${{ github.run_number }}"
        GITHUB_PACKAGES_PAT: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload vcpkg build logs
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: vcpkg-logs
        path: ${{ github.workspace }}/vcpkg/buildtrees/**/*.log
    - name: Publish PR artifacts
      if: env._IS_GITHUB_RELEASE == 'false' && success()
      uses: actions/upload-artifact@v4.0.0
      with:
        name: "${{ env._RELEASE_NAME }}-${{ env._RELEASE_VERSION }}"
        path: ".dist/*.zip"
